#!/usr/bin/env python3
"""Generate crates/atbswp-core/src/record/keymap.rs from player/src/keymap.c
so the recorders translate platform key codes with exactly the table the
player uses.  CI checks the generated file is current."""
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[2]
src = (root / "player/src/keymap.c").read_text()
rows = re.findall(r"^\s*\{(\d+), (0x[0-9A-Fa-f]+), ([01]), (0x[0-9A-Fa-f]+|NOMAC)\},\s*/\* (.*?) \*/", src, re.M)
if not rows:
    sys.exit("no table rows found")

out = ["//! GENERATED by player/tools/gen_keymap_rs.py from player/src/keymap.c. Do not edit.",
       "",
       "/// (evdev, windows scancode, extended, mac virtual keycode or 0xFF).",
       "#[rustfmt::skip]",
       "pub static TABLE: &[(u16, u8, bool, u8)] = &["]
for ev, sc, ext, mac, comment in rows:
    macv = "0xFF" if mac == "NOMAC" else mac
    out.append(f"    ({ev}, {sc}, {'true' if ext == '1' else 'false'}, {macv}), // {comment}")
out += ["];", "",
        "pub fn evdev_from_win(scancode: u8, extended: bool) -> Option<u16> {",
        "    TABLE",
        "        .iter()",
        "        .find(|(_, sc, ext, _)| *sc == scancode && *ext == extended)",
        "        .map(|(e, ..)| *e)",
        "}", "",
        "pub fn evdev_from_mac(vk: u8) -> Option<u16> {",
        "    TABLE",
        "        .iter()",
        "        .find(|(_, _, _, m)| *m == vk && vk != 0xFF)",
        "        .map(|(e, ..)| *e)",
        "}", ""]
dst = root / "crates/atbswp-core/src/record/keymap.rs"
text = "\n".join(out)
if len(sys.argv) > 1 and sys.argv[1] == "--check":
    sys.exit(0 if dst.read_text() == text else "keymap.rs is stale: run player/tools/gen_keymap_rs.py")
dst.write_text(text)
print(f"wrote {dst} ({len(rows)} keys)")
