//! GENERATED by player/tools/gen_keymap_rs.py from player/src/keymap.c. Do not edit.

/// (evdev, windows scancode, extended, mac virtual keycode or 0xFF).
#[rustfmt::skip]
pub static TABLE: &[(u16, u8, bool, u8)] = &[
    (1, 0x01, false, 0x35), // ESC
    (2, 0x02, false, 0x12), // 1
    (3, 0x03, false, 0x13), // 2
    (4, 0x04, false, 0x14), // 3
    (5, 0x05, false, 0x15), // 4
    (6, 0x06, false, 0x17), // 5
    (7, 0x07, false, 0x16), // 6
    (8, 0x08, false, 0x1A), // 7
    (9, 0x09, false, 0x1C), // 8
    (10, 0x0A, false, 0x19), // 9
    (11, 0x0B, false, 0x1D), // 0
    (12, 0x0C, false, 0x1B), // MINUS
    (13, 0x0D, false, 0x18), // EQUAL
    (14, 0x0E, false, 0x33), // BACKSPACE
    (15, 0x0F, false, 0x30), // TAB
    (16, 0x10, false, 0x0C), // Q
    (17, 0x11, false, 0x0D), // W
    (18, 0x12, false, 0x0E), // E
    (19, 0x13, false, 0x0F), // R
    (20, 0x14, false, 0x11), // T
    (21, 0x15, false, 0x10), // Y
    (22, 0x16, false, 0x20), // U
    (23, 0x17, false, 0x22), // I
    (24, 0x18, false, 0x1F), // O
    (25, 0x19, false, 0x23), // P
    (26, 0x1A, false, 0x21), // LEFTBRACE
    (27, 0x1B, false, 0x1E), // RIGHTBRACE
    (28, 0x1C, false, 0x24), // ENTER
    (29, 0x1D, false, 0x3B), // LEFTCTRL
    (30, 0x1E, false, 0x00), // A
    (31, 0x1F, false, 0x01), // S
    (32, 0x20, false, 0x02), // D
    (33, 0x21, false, 0x03), // F
    (34, 0x22, false, 0x05), // G
    (35, 0x23, false, 0x04), // H
    (36, 0x24, false, 0x26), // J
    (37, 0x25, false, 0x28), // K
    (38, 0x26, false, 0x25), // L
    (39, 0x27, false, 0x29), // SEMICOLON
    (40, 0x28, false, 0x27), // APOSTROPHE
    (41, 0x29, false, 0x32), // GRAVE
    (42, 0x2A, false, 0x38), // LEFTSHIFT
    (43, 0x2B, false, 0x2A), // BACKSLASH
    (44, 0x2C, false, 0x06), // Z
    (45, 0x2D, false, 0x07), // X
    (46, 0x2E, false, 0x08), // C
    (47, 0x2F, false, 0x09), // V
    (48, 0x30, false, 0x0B), // B
    (49, 0x31, false, 0x2D), // N
    (50, 0x32, false, 0x2E), // M
    (51, 0x33, false, 0x2B), // COMMA
    (52, 0x34, false, 0x2F), // DOT
    (53, 0x35, false, 0x2C), // SLASH
    (54, 0x36, false, 0x3C), // RIGHTSHIFT
    (55, 0x37, false, 0x43), // KPASTERISK
    (56, 0x38, false, 0x3A), // LEFTALT
    (57, 0x39, false, 0x31), // SPACE
    (58, 0x3A, false, 0x39), // CAPSLOCK
    (59, 0x3B, false, 0x7A), // F1
    (60, 0x3C, false, 0x78), // F2
    (61, 0x3D, false, 0x63), // F3
    (62, 0x3E, false, 0x76), // F4
    (63, 0x3F, false, 0x60), // F5
    (64, 0x40, false, 0x61), // F6
    (65, 0x41, false, 0x62), // F7
    (66, 0x42, false, 0x64), // F8
    (67, 0x43, false, 0x65), // F9
    (68, 0x44, false, 0x6D), // F10
    (69, 0x45, false, 0x47), // NUMLOCK -> mac keypad clear
    (70, 0x46, false, 0xFF), // SCROLLLOCK
    (71, 0x47, false, 0x59), // KP7
    (72, 0x48, false, 0x5B), // KP8
    (73, 0x49, false, 0x5C), // KP9
    (74, 0x4A, false, 0x4E), // KPMINUS
    (75, 0x4B, false, 0x56), // KP4
    (76, 0x4C, false, 0x57), // KP5
    (77, 0x4D, false, 0x58), // KP6
    (78, 0x4E, false, 0x45), // KPPLUS
    (79, 0x4F, false, 0x53), // KP1
    (80, 0x50, false, 0x54), // KP2
    (81, 0x51, false, 0x55), // KP3
    (82, 0x52, false, 0x52), // KP0
    (83, 0x53, false, 0x41), // KPDOT
    (86, 0x56, false, 0x0A), // 102ND (ISO section)
    (87, 0x57, false, 0x67), // F11
    (88, 0x58, false, 0x6F), // F12
    (96, 0x1C, true, 0x4C), // KPENTER
    (97, 0x1D, true, 0x3E), // RIGHTCTRL
    (98, 0x35, true, 0x4B), // KPSLASH
    (99, 0x37, true, 0x69), // SYSRQ / print screen -> F13
    (100, 0x38, true, 0x3D), // RIGHTALT
    (102, 0x47, true, 0x73), // HOME
    (103, 0x48, true, 0x7E), // UP
    (104, 0x49, true, 0x74), // PAGEUP
    (105, 0x4B, true, 0x7B), // LEFT
    (106, 0x4D, true, 0x7C), // RIGHT
    (107, 0x4F, true, 0x77), // END
    (108, 0x50, true, 0x7D), // DOWN
    (109, 0x51, true, 0x79), // PAGEDOWN
    (110, 0x52, true, 0x72), // INSERT -> mac help
    (111, 0x53, true, 0x75), // DELETE (forward)
    (113, 0x20, true, 0x4A), // MUTE
    (114, 0x2E, true, 0x49), // VOLUMEDOWN
    (115, 0x30, true, 0x48), // VOLUMEUP
    (117, 0x59, false, 0x51), // KPEQUAL
    (119, 0x45, true, 0xFF), // PAUSE (approximation)
    (125, 0x5B, true, 0x37), // LEFTMETA -> command
    (126, 0x5C, true, 0x36), // RIGHTMETA -> right command
    (127, 0x5D, true, 0xFF), // COMPOSE / menu
    (183, 0x64, false, 0x69), // F13
    (184, 0x65, false, 0x6B), // F14
    (185, 0x66, false, 0x71), // F15
    (186, 0x67, false, 0x6A), // F16
    (187, 0x68, false, 0x40), // F17
    (188, 0x69, false, 0x4F), // F18
    (189, 0x6A, false, 0x50), // F19
    (190, 0x6B, false, 0x5A), // F20
];

pub fn evdev_from_win(scancode: u8, extended: bool) -> Option<u16> {
    TABLE
        .iter()
        .find(|(_, sc, ext, _)| *sc == scancode && *ext == extended)
        .map(|(e, ..)| *e)
}

pub fn evdev_from_mac(vk: u8) -> Option<u16> {
    TABLE
        .iter()
        .find(|(_, _, _, m)| *m == vk && vk != 0xFF)
        .map(|(e, ..)| *e)
}
